pipeline {
    agent any
    tools {
        maven 'LocalMaven'
        jdk 'LocalJDK'
    }
    stages {
        stage('Build Application') {
            steps {
                sh 'mvn -f java-tomcat-sample/pom.xml clean package'
            }
            post {
                success {
                    echo "Now Archiving the Artifacts...."
                    archiveArtifacts artifacts: '**/*.war'
                        }
                 }
           }
         stage('Deploy in Staging Environment'){
            steps{
                build job: 'Deploy_Application_Staging_Environment'
            }
        }
         stage('Deploy in Production Environment'){
            steps{
                  timeout(time:5, unit:'DAYS'){
                    input message: 'APPROVE Production Deployment ?'
                 }
                build job: 'Deploy_Application_Production_Environment'
            }
        }

    }
}
